
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.OutputStreamWriter;
import java.io.Serializable;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guilhermeteixeira
 */
public class financeiro extends javax.swing.JFrame implements Serializable {

    DecimalFormat df = new DecimalFormat("0.##"); 
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date d = new Date();
    /**
     * Creates new form financeiro
     */
    public financeiro() {
        initComponents();
        
        
        finances.atual temp = Estoque.allFinances.get(Estoque.allFinances.size()-1);
        brutoLabel.setText(String.valueOf("R$"+df.format(temp.valorBruto)));
        maoLabel.setText(String.valueOf("R$"+df.format(temp.valorProdutos)));
        proLabel.setText(String.valueOf("R$"+df.format(temp.prolabore)));
        gastosLabel.setText(String.valueOf("R$"+df.format(temp.valorCustos)));
        if (Estoque.allFinances.size()>1){
            temp = Estoque.allFinances.get(Estoque.allFinances.size()-2);
            vendasPassLabel.setText(String.valueOf("R$"+df.format(temp.valorBruto)));
            proPassLabel.setText(String.valueOf("R$"+df.format(temp.prolabore)));
            gastosPassLabel.setText(String.valueOf("R$"+df.format(temp.valorCustos)));
            liquidoPassLabel.setText(String.valueOf("R$"+df.format(temp.valorLiquido)));
        }
    }
    private String filterVal(String val){
        if(val.indexOf(",") != -1 && val.indexOf(".") != -1){
            val = val.substring(0,val.indexOf('.'))+val.substring(val.indexOf('.')+1);
            val = val.replace(',', '.');
        }
        else if(val.indexOf(",") != -1){
            val = val.replace(',', '.');
        }
        return val;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        infoVendasBtn = new javax.swing.JButton();
        prolaboreButton = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        brutoLabel = new javax.swing.JLabel();
        maoLabel = new javax.swing.JLabel();
        proLabel = new javax.swing.JLabel();
        gastosLabel = new javax.swing.JLabel();
        createExpenseButton = new javax.swing.JButton();
        verCustosButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vendasPassLabel = new javax.swing.JLabel();
        proPassLabel = new javax.swing.JLabel();
        gastosPassLabel = new javax.swing.JLabel();
        liquidoPassLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        exportCurrentMonthButton = new javax.swing.JButton();
        errorTextField = new javax.swing.JTextField();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finanças");

        jButton1.setText("<html><center>Fechar<br />Janela</center></html>");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 45));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 45));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 45));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        infoVendasBtn.setText("<html><center>Informação<br />de Vendas</center></html>");
        infoVendasBtn.setMaximumSize(new java.awt.Dimension(100, 45));
        infoVendasBtn.setMinimumSize(new java.awt.Dimension(100, 45));
        infoVendasBtn.setPreferredSize(new java.awt.Dimension(100, 45));
        infoVendasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoVendasBtnActionPerformed(evt);
            }
        });

        prolaboreButton.setText("<html><center>Alterar<br/>Pró-labore</center></html>");
        prolaboreButton.setMaximumSize(new java.awt.Dimension(100, 45));
        prolaboreButton.setMinimumSize(new java.awt.Dimension(100, 45));
        prolaboreButton.setPreferredSize(new java.awt.Dimension(100, 45));
        prolaboreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prolaboreButtonActionPerformed(evt);
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação Deste Mês"));

        jLabel2.setText("Valor Bruto de Vendas");

        jLabel3.setText("Valor Total de Produtos em Mão");

        jLabel4.setText("Prolabore");

        jLabel5.setText("Valor Total de Gastos da Empresa");

        brutoLabel.setText(" ");

        maoLabel.setText(" ");
        maoLabel.setToolTipText("Valor estimado na adição de todos os produtos listos no estoque com o valor final em dinheiro (excluindo a taxa de 12% da maquina de cartão).");

        proLabel.setText(" ");
        proLabel.setToolTipText("Valor estimado do Pró-labore. Para alterar este valor, clique no botão abaixo: \"Alterar Pró-labore.\"");

        gastosLabel.setText(" ");

        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(brutoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(maoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(proLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(gastosLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(proLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gastosLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brutoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brutoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(proLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gastosLabel))
                .addGap(16, 16, 16))
        );

        createExpenseButton.setText("<html><center>Gerar<br />Despesa</center></html>");
        createExpenseButton.setMaximumSize(new java.awt.Dimension(100, 45));
        createExpenseButton.setMinimumSize(new java.awt.Dimension(100, 45));
        createExpenseButton.setPreferredSize(new java.awt.Dimension(100, 45));
        createExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createExpenseButtonActionPerformed(evt);
            }
        });

        verCustosButton.setText("<html><center>Abrir todas<br/>Despesas</center></html>");
        verCustosButton.setMaximumSize(new java.awt.Dimension(130, 45));
        verCustosButton.setMinimumSize(new java.awt.Dimension(130, 45));
        verCustosButton.setPreferredSize(new java.awt.Dimension(130, 45));
        verCustosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCustosButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Fechar Mês");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 45));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 45));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 45));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mês Passado"));

        jLabel1.setText("Valor Bruto de Vendas");

        jLabel6.setText("Valor Liquido de Vendas");

        jLabel7.setText("Prolabore");

        jLabel8.setText("Valor Total de Gastos da Empresa");

        vendasPassLabel.setText(" ");

        proPassLabel.setText(" ");

        gastosPassLabel.setText(" ");

        liquidoPassLabel.setText(" ");

        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(vendasPassLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(proPassLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(gastosPassLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(liquidoPassLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vendasPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(proPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gastosPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(liquidoPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vendasPassLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(proPassLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gastosPassLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(liquidoPassLabel))
                .addGap(15, 15, 15))
        );

        jButton4.setText("<html><center>Abrir Outros<br />Meses</center></html>");
        jButton4.setMaximumSize(new java.awt.Dimension(100, 45));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 45));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 45));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        exportCurrentMonthButton.setText("<html><center>Exportar<br />Planilha</center></html>");
        exportCurrentMonthButton.setMaximumSize(new java.awt.Dimension(100, 45));
        exportCurrentMonthButton.setMinimumSize(new java.awt.Dimension(100, 45));
        exportCurrentMonthButton.setPreferredSize(new java.awt.Dimension(100, 45));
        exportCurrentMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportCurrentMonthButtonActionPerformed(evt);
            }
        });

        errorTextField.setEditable(false);
        errorTextField.setAutoscrolls(false);
        errorTextField.setDragEnabled(false);
        errorTextField.setFocusable(false);
        errorTextField.setMaximumSize(new java.awt.Dimension(675, 28));
        errorTextField.setMinimumSize(new java.awt.Dimension(675, 28));
        errorTextField.setPreferredSize(new java.awt.Dimension(675, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoVendasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prolaboreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(verCustosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exportCurrentMonthButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLayeredPane3)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane3)
                    .addComponent(jLayeredPane2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(infoVendasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prolaboreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(verCustosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportCurrentMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prolaboreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prolaboreButtonActionPerformed
        // TODO add your handling code here:
        final JOptionPane optionPane = new JOptionPane();
        optionPane.setVisible(true);
        String val = (String)JOptionPane.showInputDialog(
                    optionPane,
                    "Entre seu prolabore:",
                    "Prolabore",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    null,
                    0.00);
        if(val.indexOf(",") != -1 && val.indexOf(".") != -1){
            val = val.substring(0,val.indexOf('.'))+val.substring(val.indexOf('.')+1);
            val = val.replace(',', '.');
        }
        else if(val.indexOf(",") != -1){
            val = val.replace(',', '.');
        }
        float newPro = Float.parseFloat(val);
        Estoque.allFinances.get(Estoque.allFinances.size()-1).prolabore = newPro;
        
        proLabel.setText(String.valueOf("R$"+Estoque.allFinances.get(Estoque.allFinances.size()-1).prolabore));
    }//GEN-LAST:event_prolaboreButtonActionPerformed

    private void createExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createExpenseButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gerarDespesas().setVisible(true);
            }
        });
    }//GEN-LAST:event_createExpenseButtonActionPerformed

    private void verCustosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCustosButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verCustos().setVisible(true);
            }
        });
    }//GEN-LAST:event_verCustosButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        finances f = new finances();
        float prodVal = Estoque.allFinances.get(Estoque.allFinances.size()-1).valorProdutos;
        float pro = Estoque.allFinances.get(Estoque.allFinances.size()-1).prolabore;
        float liquido = Estoque.allFinances.get(Estoque.allFinances.size()-1).valorBruto - 
                Estoque.allFinances.get(Estoque.allFinances.size()-1).valorCustos - pro;
        String dateFinal = dateFormat.format(d);
        
        Estoque.allFinances.get(Estoque.allFinances.size()-1).end = dateFinal;
        Estoque.allFinances.get(Estoque.allFinances.size()-1).valorLiquido = liquido;
        finances.atual newAtual = f.new atual(pro, prodVal);
        
        Estoque.allFinances.add(newAtual);
        finances.atual temp = Estoque.allFinances.get(Estoque.allFinances.size()-1);
        brutoLabel.setText(String.valueOf("R$"+df.format(temp.valorBruto)));
        maoLabel.setText(String.valueOf("R$"+df.format(temp.valorProdutos)));
        proLabel.setText(String.valueOf("R$"+df.format(temp.prolabore)));
        gastosLabel.setText(String.valueOf("R$"+df.format(temp.valorCustos)));
        if (Estoque.allFinances.size()>1){
            temp = Estoque.allFinances.get(Estoque.allFinances.size()-2);
            vendasPassLabel.setText(String.valueOf("R$"+df.format(temp.valorBruto)));
            proPassLabel.setText(String.valueOf("R$"+df.format(temp.prolabore)));
            gastosPassLabel.setText(String.valueOf("R$"+df.format(temp.valorCustos)));
            liquidoPassLabel.setText(String.valueOf("R$"+df.format(temp.valorLiquido)));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void infoVendasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoVendasBtnActionPerformed
        // TODO add your handling code here:
        
        verVendas.main(null);
        
    }//GEN-LAST:event_infoVendasBtnActionPerformed

    private void exportCurrentMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportCurrentMonthButtonActionPerformed
        // TODO add your handling code here:
        finances.atual temp = Estoque.allFinances.get(Estoque.allFinances.size()-1);
        String date = temp.start;
        date = date+" - "+temp.end;
        float pro = temp.prolabore;
        float vendas = temp.valorBruto;
        float gastos = temp.valorCustos;
        String[] headerGeral = {"Mês","Pró-labore","Total de Vendas", "Total de Despesas"};
        String[] headerVendas = {"Cliente","Data","Valor"};
        String[] headerVendasDetails = {"Cliente","Produto", "Descrição", "Gênero", "Valor", "Quantidade"};
        String[] headerDespesas = {"Data","Despesa", "Valor"};
        try{
            System.setProperty("file.encoding","UTF-8");
            BufferedWriter csvWriter = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("Informação Financeira deste Mês.csv", true), StandardCharsets.UTF_8));
            //FileWriter csvWriter = new FileWriter("Informação Financeira deste Mês.csv");
            
            csvWriter.append("Informação Geral do Mês:");
            csvWriter.append("\n");
            csvWriter.append("\n");
            for(String s: headerGeral){
                csvWriter.append(s);
                csvWriter.append(",");
            }
            csvWriter.append("\n");
            csvWriter.append(date);
            csvWriter.append(",");
            csvWriter.append(String.valueOf(pro));
            csvWriter.append(",");
            csvWriter.append(String.valueOf(vendas));
            csvWriter.append(",");
            csvWriter.append(String.valueOf(gastos));
            
            csvWriter.append("\n");
            csvWriter.append("\n");
            csvWriter.append("Informação de Geral de Vendas");
            csvWriter.append("\n");
            csvWriter.append("\n");
            ArrayList<finances.compra> tempVendas = temp.vendas;
            
            for(String s: headerVendas){
                csvWriter.append(s);
                csvWriter.append(",");
            }
            csvWriter.append("\n");
            for(finances.compra c:tempVendas){
                csvWriter.append(c.nomeClient);
                csvWriter.append(",");
                csvWriter.append(c.data);
                csvWriter.append(",");
                csvWriter.append(String.valueOf(c.valorTotal));
                csvWriter.append("\n");
            }
            csvWriter.append("\n");
            csvWriter.append("\n");
            csvWriter.append("Detalhes de Vendas");
            csvWriter.append("\n");
            csvWriter.append("\n");
            
            //{"Cliente","Produto", "Descrição", "Gênero", "Valor", "Quantidade"};
            for(String s: headerVendasDetails){
                csvWriter.append(s);
                csvWriter.append(",");
            }
            csvWriter.append("\n");
            for(finances.compra c:tempVendas){
                for(produtos.produto p:c.prod){
                    csvWriter.append(c.nomeClient);
                    csvWriter.append(",");
                    csvWriter.append(p.nome);
                    csvWriter.append(",");
                    csvWriter.append(p.desc);
                    csvWriter.append(",");
                    csvWriter.append(p.sexo);
                    csvWriter.append(",");
                    csvWriter.append(String.valueOf(p.valor.valor_final));
                    csvWriter.append(",");
                    csvWriter.append(String.valueOf(p.quantidade));
                    csvWriter.append("\n");
                }
            }
            
            csvWriter.append("\n");
            csvWriter.append("\n");
            csvWriter.append("Detalhes de Despesas");
            //{"Data","Despesa", "Valor"};
            csvWriter.append("\n");
            csvWriter.append("\n");
            for(String s: headerDespesas){
                csvWriter.append(s);
                csvWriter.append(",");
            }
            csvWriter.append("\n");
            for(finances.custoItems cI:temp.custos){
                csvWriter.append(cI.data);
                csvWriter.append(",");
                csvWriter.append(cI.nome);
                csvWriter.append(",");
                csvWriter.append(String.valueOf(cI.valor));
                csvWriter.append("\n");
            }
            csvWriter.close();
            
        }catch(Exception e){
            errorTextField.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_exportCurrentMonthButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mesesPassados.main(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new financeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel brutoLabel;
    private javax.swing.JButton createExpenseButton;
    private javax.swing.JTextField errorTextField;
    private javax.swing.JButton exportCurrentMonthButton;
    public static javax.swing.JLabel gastosLabel;
    private javax.swing.JLabel gastosPassLabel;
    private javax.swing.JButton infoVendasBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLabel liquidoPassLabel;
    public static javax.swing.JLabel maoLabel;
    private javax.swing.JLabel proLabel;
    private javax.swing.JLabel proPassLabel;
    private javax.swing.JButton prolaboreButton;
    private javax.swing.JLabel vendasPassLabel;
    private javax.swing.JButton verCustosButton;
    // End of variables declaration//GEN-END:variables
}
