
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guilhermeteixeira
 */
public class realizarVenda extends javax.swing.JFrame {
    
    ArrayList<produtos.produto> prodDisponivel = new ArrayList<>();
    public static ArrayList<produtos.produto> compra = new ArrayList<>();
    public static produtos.produto productToBuy;
    /**
     * Creates new form realizarVenda
     */
    public realizarVenda() {
        initComponents();
        for(produtos.produto p : Estoque.allProdArray){
            if(p.quantidade>0){
                prodDisponivel.add(p);
                vendaComboBox.addItem(p.nome);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vendaComboBox = new javax.swing.JComboBox<>();
        valoresButton = new javax.swing.JButton();
        maisProdButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        proxButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        qntSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        errorTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        carrinhoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Produtos para Venda");

        jLabel1.setText("Selectionar Produto");

        vendaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        vendaComboBox.setToolTipText("Selecionar Produto Para Venda");
        vendaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaComboBoxActionPerformed(evt);
            }
        });

        valoresButton.setText("<html><center>Informação de<br />Preço</center></html>");
        valoresButton.setMaximumSize(new java.awt.Dimension(130, 45));
        valoresButton.setMinimumSize(new java.awt.Dimension(130, 45));
        valoresButton.setPreferredSize(new java.awt.Dimension(130, 45));
        valoresButton.setSize(new java.awt.Dimension(130, 45));
        valoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valoresButtonActionPerformed(evt);
            }
        });

        maisProdButton.setText("<html><center>Adicionar<br />Produto</center></html>");
        maisProdButton.setMaximumSize(new java.awt.Dimension(130, 45));
        maisProdButton.setMinimumSize(new java.awt.Dimension(130, 45));
        maisProdButton.setPreferredSize(new java.awt.Dimension(130, 45));
        maisProdButton.setSize(new java.awt.Dimension(130, 45));
        maisProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisProdButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Descrição");

        nomeLabel.setText(" ");

        descLabel.setText(" ");

        proxButton.setText("<html><center>Ver<br />Carrinho</center></html>");
        proxButton.setMaximumSize(new java.awt.Dimension(130, 45));
        proxButton.setMinimumSize(new java.awt.Dimension(130, 45));
        proxButton.setPreferredSize(new java.awt.Dimension(130, 45));
        proxButton.setSize(new java.awt.Dimension(130, 45));
        proxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade");

        qntSpinner.setModel(new javax.swing.SpinnerNumberModel());

        jButton1.setText("Cancelar");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 45));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 45));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 45));
        jButton1.setSize(new java.awt.Dimension(130, 45));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        errorTextField.setEditable(false);

        jLabel5.setText("Produtos Adicionados");

        carrinhoTextField.setEditable(false);
        carrinhoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        carrinhoTextField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorTextField)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(valoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maisProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(vendaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(qntSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carrinhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(vendaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nomeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(descLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(qntSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carrinhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(maisProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valoresButtonActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.##");
        
        int produto = vendaComboBox.getSelectedIndex();
        
        produtos.produto productToBuy = prodDisponivel.get(produto-1);
        String nome = productToBuy.nome;
        float item = productToBuy.valor.valor_item; // em dolares mostrar valor_item
        float valFinal = productToBuy.valor.valor_final; // em dolares mostrar valor_item
        float lucro = productToBuy.valor.lucro; //mostrar os 80% de lucro
        float imposto = productToBuy.valor.imposto; // valor pago de imposto
        float transporte = productToBuy.valor.transporte; // valor pago em transporte
        float valReal = productToBuy.valor.valor_item_real; // valor final
        float valCard = (float)(valFinal+valFinal*0.12);
        
       
        final JOptionPane optionPane = new JOptionPane(
        "Valor pago em dolar: $"+df.format(item)
        + "\nValor pago em transporte: R$"+df.format(transporte)
        + "\nValor pago em imposto: R$"+df.format(imposto)
        + "\nCusto 0: R$"+df.format(lucro)
        + "\nValor final do produto: R$"+df.format(valFinal),
        JOptionPane.QUESTION_MESSAGE,
        JOptionPane.YES_NO_OPTION);
        optionPane.setVisible(true);
        
        Object[] options = {"Fechar"};
        int n = JOptionPane.showOptionDialog(optionPane,
            "Valor pago em dolar: $"+df.format(item)
        + "\nValor pago em real: R$"+df.format(valReal)
        + "\nValor pago em transporte: R$"+df.format(transporte)
        + "\nValor pago em imposto: R$"+df.format(imposto)
        + "\nCusto 0: R$"+df.format(lucro)
        + "\nValor final do produto em dinheiro: R$"+df.format(valFinal)
        +"\nValor final do produto no cartão (+12%): R$"+df.format(valCard),
            "Valores: " +nome,
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);
    }//GEN-LAST:event_valoresButtonActionPerformed

    private void vendaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaComboBoxActionPerformed
        // TODO add your handling code here:
        int produto = vendaComboBox.getSelectedIndex();
        if(produto>0){
            produtos.produto productToBuy = prodDisponivel.get(produto-1);
            nomeLabel.setText(productToBuy.nome);
            descLabel.setText(productToBuy.desc);
            // SpinnerNumberModel(start, minimum value, maximum value, increase by value);
            SpinnerNumberModel model1 = new SpinnerNumberModel(1, 1, productToBuy.quantidade, 1); 
            qntSpinner.setModel(model1);
        }
    }//GEN-LAST:event_vendaComboBoxActionPerformed

    private void maisProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisProdButtonActionPerformed
        // TODO add your handling code here:
        try{
        produtos p = new produtos();
        int produto = vendaComboBox.getSelectedIndex();
        produtos.produto productToBuy = p.new produto(prodDisponivel.get(produto-1));
        
        productToBuy.quantidade = (Integer)qntSpinner.getValue();
        compra.add(productToBuy);
        vendaComboBox.setSelectedIndex(0);
        qntSpinner.setValue(1);
        nomeLabel.setText(" ");
        descLabel.setText(" ");
        carrinhoTextField.setText(String.valueOf(compra.size()));
        errorTextField.setText("");
        }catch(Exception e){
            errorTextField.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_maisProdButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void proxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxButtonActionPerformed
        // TODO add your handling code here:
        if(compra.size()>0){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new finalizarCompra().setVisible(true);
                }
            });
            this.dispose();
        }
        else{
            errorTextField.setText("Adicione pelo menos um produto no carrinho.");
        }
    }//GEN-LAST:event_proxButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(realizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(realizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(realizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(realizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new realizarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carrinhoTextField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField errorTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton maisProdButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton proxButton;
    private javax.swing.JSpinner qntSpinner;
    private javax.swing.JButton valoresButton;
    private javax.swing.JComboBox<String> vendaComboBox;
    // End of variables declaration//GEN-END:variables
}
