
import java.io.Serializable;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guilhermeteixeira
 */
public class remessa extends javax.swing.JFrame implements Serializable {
    String data = remessaInfo.date;
    String transporte = remessaInfo.transp;
    float dolar = remessaInfo.cotDolar;
    float imposto = remessaInfo.imposto;
    float frete = remessaInfo.frete;
    DecimalFormat df = new DecimalFormat("0.##");
    
    int counter = 0;
    produtos prodClass = new produtos();
    produtos.list_produtos all_prod = prodClass.new list_produtos();
    ArrayList<produtos.produto> tempProds = new ArrayList<>();
    ArrayList<String> prodNames = new ArrayList<String>();
    
    /**
     * Creates new form remessa
     */
    public remessa() {
        initComponents();
        
        remessa.idRemessaTextField.setText(String.valueOf(Estoque.totalPacotes+1));
        dolarLabel.setText("Cotação do dolar: R$"+String.valueOf(remessaInfo.cotDolar));
        for(produtos.produto p : Estoque.allProdArray){
            produtosExistentesComboBox.addItem(p.nome);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelarButton = new javax.swing.JButton();
        salvarRemessaButton = new javax.swing.JButton();
        proxProdButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idRemessaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        produtosExistentesComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        descTextField = new javax.swing.JTextField();
        sizeComboBox = new javax.swing.JComboBox<>();
        sexoComboBox = new javax.swing.JComboBox<>();
        storeComboBox = new javax.swing.JComboBox<>();
        departmentComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        resetarCamposButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        counterTextField = new javax.swing.JTextField();
        errorTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        qntSpinner = new javax.swing.JSpinner();
        dolarLabel = new javax.swing.JLabel();
        valorFormattedTextField = new javax.swing.JTextField();
        vendaFormattedTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar Produtos");

        cancelarButton.setText("Cancelar");
        cancelarButton.setToolTipText("Cancela o pacote e deleta todos os produtos adicionado neste pacote");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        salvarRemessaButton.setText("Salvar Pacote");
        salvarRemessaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarRemessaButtonActionPerformed(evt);
            }
        });

        proxProdButton.setText("Salvar Produto");
        proxProdButton.setToolTipText("Adicionar produtor e ir ao próximo");
        proxProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxProdButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Pacote");

        idRemessaTextField.setEditable(false);
        idRemessaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRemessaTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Incluir produto existente");

        produtosExistentesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        produtosExistentesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosExistentesComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        jLabel4.setText("Descrição");

        jLabel5.setText("Departamento");

        jLabel6.setText("Gênero");

        jLabel7.setText("Loja");

        jLabel8.setText("Tamanho");

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "N/A", "RN", "3M", "6M", "9M", "12M", "18M", "24M", "2T", "3T", "4T", "5T", "10T", "11T", "12T", "13T", "14T" }));

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Neutro", "Masculino", "Feminino" }));

        storeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Amazon", "Avent", "Carter's", "CVS", "Disney", "Fisher Price", "Graco", "Kipling", "NUK", "Pampers", "Oshkosh", "Skip Hop", "Walgreens", "Walmart", "Target", "Outros" }));

        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Acessesórios", "Alimentação", "Brinquedos", "Eletrônicos", "Farmacia", "Higiene", "Mochilas", "Passeio", "Roupas", "Segurança" }));

        jLabel9.setText("Valor Pago");

        resetarCamposButton.setText("Resetar Todos os Campos");
        resetarCamposButton.setToolTipText("Limpar todos os campos");
        resetarCamposButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarCamposButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Produtos Adicionados");

        counterTextField.setEditable(false);
        counterTextField.setText("0");
        counterTextField.setToolTipText("Numero de produtos adicionado ao novo pacote");

        errorTextField.setEditable(false);
        errorTextField.setToolTipText("Mensagem de erro");

        jLabel11.setText("Valor de Venda");

        jLabel12.setText("Quantidade");

        qntSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        valorFormattedTextField.setText("0");

        vendaFormattedTextField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(counterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(proxProdButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetarCamposButton)
                                .addGap(42, 42, 42)
                                .addComponent(salvarRemessaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idRemessaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtosExistentesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dolarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qntSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                .addComponent(nameTextField))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vendaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(valorFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dolarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(idRemessaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(produtosExistentesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(qntSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(valorFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(counterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(vendaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(salvarRemessaButton)
                    .addComponent(proxProdButton)
                    .addComponent(resetarCamposButton))
                .addGap(4, 4, 4)
                .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void clearAllFields(){
        nameTextField.setText("");
        descTextField.setText("");
        departmentComboBox.setSelectedIndex(0);
        storeComboBox.setSelectedIndex(0);
        sexoComboBox.setSelectedIndex(0);
        sizeComboBox.setSelectedIndex(0);
        valorFormattedTextField.setText("0.00");
        valorFormattedTextField.setText("0.00");
        qntSpinner.setValue(0);
        produtosExistentesComboBox.setSelectedIndex(0);
    }
    private String filterVal(String val){
        if(val.indexOf(",") != -1 && val.indexOf(".") != -1){
            val = val.substring(0,val.indexOf('.'))+val.substring(val.indexOf('.')+1);
            val = val.replace(',', '.');
        }
        else if(val.indexOf(",") != -1){
            val = val.replace(',', '.');
        }
        return val;
    }
    
    private void proxProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxProdButtonActionPerformed
        // TODO add your handling code here:
        try{
        String val = valorFormattedTextField.getText(); // valor de compra em dolares
        val = filterVal(val);
        String val2 = vendaFormattedTextField.getText(); // valor final para vender
        val2 = filterVal(val2);
        String nome = String.valueOf(nameTextField.getText());
        String desc = String.valueOf(descTextField.getText());
        String dpt = departmentComboBox.getItemAt(departmentComboBox.getSelectedIndex());
        String loja = storeComboBox.getItemAt(storeComboBox.getSelectedIndex());
        String gender =  sexoComboBox.getItemAt(sexoComboBox.getSelectedIndex());
        String size = sizeComboBox.getItemAt(sizeComboBox.getSelectedIndex());
        float valor = Float.parseFloat(val); //valor de compra em dolares
        float venda = Float.parseFloat(val2); // valor final para vender
        int qnt = (int) qntSpinner.getValue();
        if(nome.equals("") || desc.equals("") || dpt.equals("-") || 
                size.equals("-") || valor == 0.00f || loja.equals("-")){
                errorTextField.setText("Confirme que todos os campos de informação estajam preenchidos.");
        }
        else{
            produtos prod = new produtos();
            produtos.produto temp = prod.new produto(nome,desc,loja,dpt,size,qnt,gender,Estoque.totalPacotes+1);
            temp.valor = prod.new precos(valor,dolar,venda);

            tempProds.add(temp);
            prodNames.add(nome);
            
            counter++;
            counterTextField.setText(String.valueOf(counter));
            errorTextField.setText(String.valueOf(""));
            
            clearAllFields();
        }
        }catch(Exception e){
            errorTextField.setText(String.valueOf(String.valueOf(e)));
        }
        
    }//GEN-LAST:event_proxProdButtonActionPerformed

    private void resetarCamposButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarCamposButtonActionPerformed
        // TODO add your handling code here:
        clearAllFields();
    }//GEN-LAST:event_resetarCamposButtonActionPerformed

    private void idRemessaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRemessaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRemessaTextFieldActionPerformed

    private void produtosExistentesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosExistentesComboBoxActionPerformed
        // TODO add your handling code here:
        String produto = produtosExistentesComboBox.getItemAt(produtosExistentesComboBox.getSelectedIndex());
        if(!produto.equals("-")){
            produtos.produto prod = null;
            for(produtos.produto p:Estoque.allProdArray){
                if(produto.contains(p.nome) || p.nome.contains(produto)){
                    prod = p;
                    break;
                }
            }
            int i;

            nameTextField.setText(prod.nome);
            descTextField.setText(prod.desc);

            for(i = 0;i<departmentComboBox.getItemCount();i++){
                if(departmentComboBox.getItemAt(i).equals(prod.dept)) break;
            }
            departmentComboBox.setSelectedIndex(i);

            for(i = 0;i<storeComboBox.getItemCount();i++){
                if(storeComboBox.getItemAt(i).equals(prod.loja)) break;
            }
            storeComboBox.setSelectedIndex(i);

            for(i = 0;i<sexoComboBox.getItemCount();i++){
                if(sexoComboBox.getItemAt(i).equals(prod.sexo)) break;
            }
            sexoComboBox.setSelectedIndex(i);

            for(i = 0;i<sizeComboBox.getItemCount();i++){
                if(sizeComboBox.getItemAt(i).equals(prod.tamanho)) break;
            }
            sizeComboBox.setSelectedIndex(i);

            //valorFormattedTextField.setText(String.valueOf(prod.valor.valor_final));
            valorFormattedTextField.setText(String.valueOf(prod.valor.valor_item));
        }
        else{
            clearAllFields();
        }
    }//GEN-LAST:event_produtosExistentesComboBoxActionPerformed

    private void salvarRemessaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarRemessaButtonActionPerformed
        // TODO add your handling code here:
        try{
        produtos p = new produtos();
        produtos.remessa novoPct = p.new remessa();
        float total = 0.0f;
        for(produtos.produto s: tempProds){
            total+=Float.parseFloat(filterVal(String.valueOf(s.valor.valor_item)));
        }
        novoPct.data = data;
        novoPct.id = Estoque.totalPacotes+1;
        novoPct.dolar = dolar;
        novoPct.total_dolar = total;
        novoPct.total_real = total*dolar;
        novoPct.imposto = imposto;
        novoPct.frete = frete;
        
        
        for(produtos.produto s:tempProds){
            s.valor.porcentagem_do_total = s.valor.valor_item_real/novoPct.total_real; 
            s.valor.transporte = novoPct.frete*s.valor.porcentagem_do_total;
            s.valor.imposto = novoPct.imposto*s.valor.porcentagem_do_total;
            s.valor.valor_item_real = s.valor.valor_item*dolar;
            s.valor.imposto = imposto*s.valor.porcentagem_do_total;
            if(s.valor.valor_final == 0.0f){
                s.valor.valor_final = s.valor.imposto+s.valor.transporte+s.valor.valor_item_real;
                s.valor.valor_final += (s.valor.valor_final*0.8);
            }
            s.valor.lucro = s.valor.valor_item_real + s.valor.transporte + s.valor.imposto;
        }
        
        Estoque.pacotes.add(novoPct);
        Estoque.allProdArray.addAll(tempProds);
        
        Estoque.totalPacotes++;
        Estoque.MSGTextField.setText(String.valueOf(Estoque.totalPacotes));
        Estoque.reCalculateTotalProd();
        this.dispose();
        }catch(Exception e){
            errorTextField.setText(String.valueOf(String.valueOf(e)));
        }
    }//GEN-LAST:event_salvarRemessaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(remessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(remessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(remessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(remessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remessa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField counterTextField;
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JTextField descTextField;
    private javax.swing.JLabel dolarLabel;
    private javax.swing.JTextField errorTextField;
    public static javax.swing.JTextField idRemessaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    public static javax.swing.JComboBox<String> produtosExistentesComboBox;
    private javax.swing.JButton proxProdButton;
    private javax.swing.JSpinner qntSpinner;
    private javax.swing.JButton resetarCamposButton;
    private javax.swing.JButton salvarRemessaButton;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JComboBox<String> storeComboBox;
    private javax.swing.JTextField valorFormattedTextField;
    private javax.swing.JTextField vendaFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
